source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.5.1"

gem "mongoid"

gem "activeadmin"
gem "acts-as-taggable-on"
gem "annotate"
gem "aws-sdk-core"
gem "aws-sdk-rails"
gem "aws-sdk-s3", require: false
gem "bcrypt", "~> 3.1.7"
gem "biz"
gem "bootsnap", ">= 1.1.0", require: false
gem "bootstrap", "~> 4.1.1"
gem "bootstrap_form"
gem "bson_ext"
gem "bullet"
gem "cancancan"
gem "carrierwave"
gem "chartkick"
gem "config"
gem "database_cleaner"
gem "database_rewinder"
gem "devise"
gem "devise_invitable"
gem "devise_token_auth"
gem "dotenv-rails"
gem "draper"
gem "elasticsearch-model"
gem "elasticsearch-rails"
gem "enum_help"
gem "enumerize"
gem "font-awesome-rails"
gem "geocoder"
gem "google-analytics-rails"
gem "hirb"
gem "http"
gem "jbuilder", "~> 2.5"
gem "jquery-rails"
gem "kaminari"
gem "line-bot-api"
gem "mechanize"
gem "meta-tags"
gem "mini_magick", "~> 4.8"
gem "money-rails"
gem "mysql2", ">= 0.4.4", "< 0.6.0"
gem "omniauth-facebook"
gem "omniauth-google-oauth2"
gem "omniauth-line"
gem "omniauth-twitter"
gem "payjp"
gem "puma", "~> 3.11"
gem "rack-attack"
gem "rack-cors"
gem "rails", "~> 5.2.1"
gem "rails-i18n"
gem "rails_best_practices"
gem "ransack"
gem "redis"
gem "redis-namespace"
gem "redis-rails"
gem "rmagick"
gem "sidekiq"
gem "sidekiq-failures"
gem "sidekiq-unique-jobs"
gem "slack-api"
gem "slack-notifier"
gem "therubyracer"
gem "unicorn"
gem "whenever"

group :development, :test do
  gem "better_errors"
  gem "binding_of_caller"
  gem "brakeman"
  gem "byebug", platforms: %i[mri mingw x64_mingw]
  gem "factory_bot_rails"
  gem "faker"
  gem "mongoid-rspec"
  gem "pry-byebug"
  gem "pry-rails"
  gem "rails-controller-testing"
  gem "reek"
  gem "rspec-rails"
  gem "rubocop"
  gem "shoulda-matchers"
  gem "test-queue"
end

group :test do
  gem "codecov", require: false
  gem "simplecov", require: false
end

group :development do
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
  gem "web-console", ">= 3.3.0"
end